use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
struct Song;

struct Db {
    queue: dbstruct::Vec<Song>,
}

impl Db {
    // normally generated by the macro
    pub fn new() -> Self {
        let db = sled::Config::default().temporary(true).open().unwrap();
        let tree = db.open_tree("test").unwrap();

        Self {
            queue: dbstruct::Vec::new(tree, 0),
        }
    }
}

fn main() {
    let db = Db::new();
    db.queue.pop().unwrap();
}
