[package]
name = "dbstruct-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"
heck = "0.4.0"
proc-macro2 = "1"
proc-macro-error = "1"
thiserror = "1"

[lib]
proc-macro = true
